apiVersion: v1
data:
  POSTGRESQLHOST: "YWlyZmxvdy1wb3N0Z3Jlc3Fs"
  POSTGRESQLUSERNAME: "Ym5fYWlyZmxvdw=="
  POSTGRESQLPASSWORD: "YWlyZmxvdw=="
  POSTGRESQLDATABASE: "Yml0bmFtaV9haXJmbG93"
  POSTGRESQLPORT: "NTQzMg=="
kind: Secret
metadata:
  name: database-secrets
type: Opaque
